# Generated by Django 5.1.2 on 2024-10-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_cuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cuit',
            new_name='cuil',
        ),
    ]
