# Generated by Django 5.1.1 on 2024-10-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedores',
            field=models.ManyToManyField(related_name='insumos', to='inventario.proveedor'),
        ),
    ]
