# Generated by Django 5.1.1 on 2024-10-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_insumo_proveedor_insumo_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cuit',
        ),
    ]
