# Generated by Django 5.1.2 on 2024-10-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayorista',
            name='cuil',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
