# Generated by Django 5.1.1 on 2024-10-21 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_mayorista_cuil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='comprobante',
            new_name='comprobante_tipo',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='pago',
            new_name='pago_tipo',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='venta',
            new_name='venta_tipo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
        ),
    ]
