# Generated by Django 5.1.1 on 2024-10-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_comprobante_venta_comprobante_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='empleado',
        ),
    ]
