# Generated by Django 5.1.1 on 2024-10-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_venta_nro_comprobante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemventa',
            options={'ordering': ['id']},
        ),
    ]
